### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Pjc78** [AntoineSoetewey/running-pace-calculator#3]
I have made some proposed improvements.

- I have added vo2max calculation
- I have added a Daniels Vdot number
-Mods to table including , splits per 100m's useful for sessions and working out rep times based on pace.

**Comment by AntoineSoetewey** [comment]
Hello @Pjc78,

I would be glad to implement your proposed improvements in the app. Feel free to propose a pull request (if you wish to share your work of course!).

Regards,
Antoine
